language: node_js

node_js:
  - "6"
  - "8"
  - "10"

cache:
  directories:
    - node_modules
    - example/node_modules

script:
  - npm test
  - cd example
  - npm install
  - npm run lint

after_success:
  - npm run docu
